### ISSUE TITLE
lodash instrumentation compile error

### ISSUE THREAD

**Issue by chrissrogers** [codegl/tracegl#14] opened 2013-04-24 00:50 UTC
I encounter the following error when attempting to instrument the [lodash](https://github.com/bestiejs/lodash) library. dist/lodash.js is the code imported by node, and the following results in any application that utilizes lodash being uninstrumentable.

``` bash
$ tracejs node_modules/lodash/dist/lodash.js
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...up to date.

node_modules/lodash/dist/lodash.js:2116
      (;(_$_b.b804=(_$_.c(805,hasOwnProperty.call(result, key)))) ? result[key
       ^
SyntaxError: Unexpected token ;
    at Module._compile (module.js:439:25)
    at Module.m._compile (/Users/chrisrogers/trace.js:42:22)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at Function.require (module.js:380:17)
    at nodeLoader (/Users/chrisrogers/trace.js:48:10)
    at Object./trace/trace_server (/Users/chrisrogers/trace.js:23:65)
    at Object.<anonymous> (/Users/chrisrogers/trace.js:13516:38)
```

**Comment by shaunxcode** [comment] 2013-04-24 00:53
This is a caused by the same issue as reported in https://github.com/codegl/tracegl/issues/5

**Comment by chrissrogers** [comment] 2013-04-24 01:05
Specific to this case, the instrumentation seems to be taking issue with this syntax -> https://github.com/bestiejs/lodash/blob/c41bd030977c7a07fc3c562b549507a3429a4a52/dist/lodash.js#L2093

I have been able to reliably replicate the issue by instrumenting the following ternary-in-parens patterns

``` js
// The following produce the observed error
(x ? 'a' : 'b');
(x ? 'a' : 'b')

// These do not
var z = (x ? 'a' : 'b');
{ z: (x ? 'a' : 'b') };
```

**Comment by codegl** [comment] 2013-04-29 15:16
This should be fixed now.

**Closed as completed by codegl** 2013-04-29 15:16 UTC

**Comment by chrissrogers** [comment] 2013-04-29 15:26
Indeed, I can verify that instrumentation works now. Cheers!
